---
- name: Install Security Tools on Ubuntu
  hosts: all
  become: true  # Run tasks with elevated privileges

  tasks:
    - name: Update the apt package cache
      apt:
        update_cache: yes

    - name: Install UFW and Fail2Ban
      apt:
        name:
          - ufw
          - fail2ban
        state: present

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny  # Default deny policy for incoming traffic

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Ensure Fail2Ban service is running
      service:
        name: fail2ban
        state: started
        enabled: true

