---
- name: Configure newly installed Ubuntu VM
  hosts: all
  become: true
  tasks:

    # Ensure UFW firewall is installed
    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    # Enable and start UFW firewall
    - name: Enable UFW firewall
      command: ufw enable

    # Allow only SSH connection through UFW
    - name: Allow SSH connection
      command: ufw allow OpenSSH

    # Block all other incoming traffic
    - name: Block all other incoming traffic
      command: ufw default deny incoming

    # Install PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # Start and enable PostgreSQL service
    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    # Set password for the 'postgres' user using command
    - name: Set PostgreSQL postgres user password
      command: "sudo -u postgres psql -c \
