---
- name: Configure newly installed Ubuntu VM
  hosts: all
  become: true
  tasks:

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    - name: Allow SSH connection
      command: ufw allow OpenSSH

    - name: Block all other incoming traffic
      command: ufw default deny incoming

    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Create a sample directory
      file:
        path: /opt/sample-directory
        state: directory
        mode: '0755'

    - name: Update the system package list
      apt:
        update_cache: yes
