---
- name: Configure newly installed Ubuntu VM
  hosts: all
  become: true
  tasks:

    # Update system package list
    - name: Update the system package list
      apt:
        update_cache: yes

    # Install UFW firewall
    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    # Allow SSH connection
    - name: Allow SSH connection
      command: ufw allow OpenSSH

    # Block all other incoming traffic
    - name: Block all other incoming traffic
      command: ufw default deny incoming

    # Install Neovim
    - name: Install Neovim
      apt:
        name: neovim
        state: present

    # Install PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # Start PostgreSQL service
    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    # Install curl
    - name: Install curl
      apt:
        name: curl
        state: present

    # Create a sample directory
    - name: Create a sample directory
      file:
        path: /opt/sample-directory
        state: directory
        mode: '0755'


- name: Clone, install, and configure fzf
  hosts: all
  become: false  # Run as the current user
  tasks:

    - name: Clone fzf repository
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ ansible_env.HOME }}/.fzf"
        depth: 1

    - name: Run fzf installation script
      shell: "{{ ansible_env.HOME }}/.fzf/install --key-bindings --completion --no-update-rc"
      args:
        executable: /bin/bash

    - name: Add fzf to shell rc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"  # Adjust if using another shell (e.g., .zshrc)
        line: |
          # Enable fzf keybindings
          [ -f "{{ ansible_env.HOME }}/.fzf.bash" ] && source "{{ ansible_env.HOME }}/.fzf.bash"
        create: yes

    - name: Source .bashrc to apply the changes
      shell: source {{ ansible_env.HOME }}/.bashrc
      args:
        executable: /bin/bash
