---
- name: Configure newly installed Ubuntu VM
  hosts: all
  become: true
  tasks:

    # Update system package list
    - name: Update the system package list
      apt:
        update_cache: yes

    # Install UFW firewall
    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    # Allow SSH connection
    - name: Allow SSH connection
      command: ufw allow OpenSSH

    # Block all other incoming traffic
    - name: Block all other incoming traffic
      command: ufw default deny incoming

    # Install Neovim
    - name: Install Neovim
      apt:
        name: neovim
        state: present

    # Install PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # Start PostgreSQL service
    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    # Install curl
    - name: Install curl
      apt:
        name: curl
        state: present

    # Create a sample directory
    - name: Create a sample directory
      file:
        path: /opt/sample-directory
        state: directory
        mode: '0755'

    # Install fzf
    - name: Install fzf
      apt:
        name: fzf
        state: present

    # Configure fzf in Bash
    - name: Configure fzf in Bash
      lineinfile:
        path: /etc/bash.bashrc
        line: |
          if [[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]]; then
            source /usr/share/doc/fzf/examples/key-bindings.bash
          fi
          export FZF_DEFAULT_COMMAND='find . -type f'

    # Install fzf keybindings and completions manually
    - name: Manually configure fzf keybindings and completions
      block:
        - name: Download fzf keybindings and completions
          get_url:
            url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash
            dest: /etc/profile.d/fzf-key-bindings.bash
            mode: '0644'

        - name: Add fzf configuration to bashrc
          lineinfile:
            path: /etc/bash.bashrc
            line: 'source /etc/profile.d/fzf-key-bindings.bash'
            state: present
