vault_system_user: "john"
vault_system_user_password: "john@123"

hosts:
  all:
    tasks:
      - name: Adding user
        user:
          name: "{{ vault_system_user }}"
          password: "{{ vault_system_user_password | password_hash('sha512') }}"
          comment: "John Ben"
          shell: /bin/bash
          group: apache
          createhome: yes
          home: "/home/{{ vault_system_user }}"
