---
- name: Create user kk
  hosts: all
  become: yes
  tasks:
    - name: Create user kk
      user:
        name: kk
        password: "{{ 'password' | password_hash('sha512') }}"
        state: present
